import { Article, Category, Language, UIStrings } from './types';

export const APP_NAME = "Nexara";

export const CATEGORIES = Object.values(Category);

export const SUPPORTED_LANGUAGES = [
  { code: Language.ENGLISH, name: 'English', native: 'English' },
  { code: Language.HINDI, name: 'Hindi', native: 'हिन्दी' },
  { code: Language.TAMIL, name: 'Tamil', native: 'தமிழ்' },
  { code: Language.TELUGU, name: 'Telugu', native: 'తెలుగు' },
  { code: Language.MALAYALAM, name: 'Malayalam', native: 'മലയാളം' },
  { code: Language.SPANISH, name: 'Spanish', native: 'Español' },
  { code: Language.FRENCH, name: 'French', native: 'Français' },
  { code: Language.GERMAN, name: 'German', native: 'Deutsch' },
  { code: Language.CHINESE, name: 'Chinese', native: '中文' },
];

// Helper for mock images - Updated to 16:9 aspect ratio (1024x576) for better UI fit
const getMockImage = (prompt: string) => `https://image.pollinations.ai/prompt/${encodeURIComponent(prompt + ' news photo realistic')}?width=1024&height=576&nologo=true`;

export const MOCK_ARTICLES: Article[] = [
  {
    id: '1',
    title: 'AI Breakthrough: New Model Solves Complex Math Problems',
    description: 'Researchers have unveiled a new artificial intelligence model capable of solving advanced mathematical theorems that have puzzled scientists for decades.',
    content: 'In a groundbreaking development, a consortium of tech giants has released a new AI model that demonstrates unprecedented reasoning capabilities. Unlike previous iterations that focused on pattern recognition, this new architecture, dubbed "MathGenius," utilizes a novel approach to symbolic logic. Tests show it can derive proofs for complex theorems in real-time. This advancement promises to accelerate progress in physics, engineering, and cryptography. Experts believe this is a significant step towards AGI. The model was trained on a vast dataset of academic papers and verified mathematical proofs, allowing it to bridge gaps in logic that human mathematicians often struggle with.',
    author: 'Sarah Jenkins',
    source: 'Tech Daily',
    url: '#',
    imageUrl: getMockImage('Artificial Intelligence Math Problem Solving'),
    publishedAt: '2025-02-15T10:00:00Z',
    category: Category.TECHNOLOGY,
    language: Language.ENGLISH
  },
  {
    id: '2',
    title: 'Global Markets Rally as Inflation Data Shows Cooling',
    description: 'Stock markets across the globe saw significant gains today after the latest inflation report came in lower than expected.',
    content: 'Investors breathed a sigh of relief as the Consumer Price Index (CPI) rose only 0.2% last month, signaling that aggressive interest rate hikes are finally curbing inflation. The S&P 500 rose by 2.5%, while Asian and European markets followed suit. Technology and consumer discretionary sectors led the rally. Central bank officials, however, remain cautious, stating that while this is positive news, the fight against inflation is not yet over. Analysts predict a potential stabilization of interest rates by the next quarter if these trends continue.',
    author: 'Michael Chen',
    source: 'Financial Times',
    url: '#',
    imageUrl: getMockImage('Stock Market Bull Rally Financial Graph'),
    publishedAt: '2025-02-14T14:30:00Z',
    category: Category.BUSINESS,
    language: Language.ENGLISH
  },
  {
    id: '3',
    title: 'Championship Finals: Underdog Team Takes the Trophy',
    description: 'In a stunning upset, the city underdogs defeated the defending champions in a thrilling overtime match.',
    content: 'The stadium erupted in cheers as the final whistle blew, marking a historic victory for the local team. Despite being down by two points in the final quarter, a miraculous comeback led by star player Rodriguez secured the win. The final score of 98-95 will be remembered for years. Fans flooded the streets in celebration, and the city has declared a public holiday to honor the new champions. The coach attributed the victory to months of disciplined defensive training and the unyielding spirit of the squad.',
    author: 'David Sport',
    source: 'Sports Central',
    url: '#',
    imageUrl: getMockImage('Sports Stadium Victory Celebration Trophy'),
    publishedAt: '2025-02-13T20:15:00Z',
    category: Category.SPORTS,
    language: Language.ENGLISH
  },
  {
    id: '4',
    title: 'New Health Guidelines for Daily Water Intake Released',
    description: 'Health organizations have updated their recommendations for daily water consumption based on recent metabolic studies.',
    content: 'Forget the "8 glasses a day" rule. New research suggests that individual hydration needs vary significantly based on activity level, climate, and physiology. The new guidelines recommend a baseline of 2.5 liters for men and 2.0 liters for women, but emphasize listening to your body\'s thirst signals. Overhydration is also noted as a potential risk. The report also highlights the importance of electrolytes in hydration, especially for athletes and those living in hotter climates.',
    author: 'Dr. Emily Carter',
    source: 'Health Weekly',
    url: '#',
    imageUrl: getMockImage('Drinking Water Health Hydration Glass'),
    publishedAt: '2025-02-12T09:00:00Z',
    category: Category.HEALTH,
    language: Language.ENGLISH
  },
  {
    id: '5',
    title: 'Election Results: Tight Race Leads to Runoff',
    description: 'The national election has ended in a deadlock, requiring a runoff vote next month to determine the next president.',
    content: 'With 99% of votes counted, neither leading candidate secured the required 50% majority. Incumbent President Doe finished with 48%, while challenger Smith secured 47%. The remaining votes went to independent candidates. The electoral commission has scheduled a runoff for November 15th. Both campaigns have already begun ramping up their efforts for what promises to be an intense few weeks of campaigning. Voter turnout was historically high, reflecting the crucial nature of this election cycle.',
    author: 'Political Staff',
    source: 'The Nation',
    url: '#',
    imageUrl: getMockImage('Politics Election Voting Ballot Box'),
    publishedAt: '2025-02-10T08:00:00Z',
    category: Category.POLITICS,
    language: Language.ENGLISH
  },
  {
    id: '6',
    title: 'Mars Colonization Project: First Habitat Module Lands',
    description: 'Space agencies celebrate a historic moment as the first automated habitat module touches down safely on the Red Planet.',
    content: 'Humanity has taken a giant leap towards interplanetary civilization. The "Ares-1" module, an autonomous life-support unit, successfully landed in the Jezero Crater today. This module will begin generating oxygen and filtering water in preparation for the first human crew, scheduled to arrive in 2029. Mission control reported optimal system performance upon landing. The module is equipped with advanced solar arrays and a small nuclear reactor to ensure power supply during Martian dust storms. This success paves the way for the subsequent launches of supply drops and the eventual arrival of the colonization team.',
    author: 'Dr. Alan Grant',
    source: 'Cosmos Weekly',
    url: '#',
    imageUrl: getMockImage('Mars Habitat Red Planet Space Landing'),
    publishedAt: '2025-02-16T11:00:00Z',
    category: Category.SCIENCE,
    language: Language.ENGLISH
  },
  {
    id: '7',
    title: 'Renewable Energy Surpasses Fossil Fuels in Global Grid',
    description: 'For the first time in history, renewable energy sources have generated more power globally than coal and gas combined.',
    content: 'A new report by the International Energy Agency confirms that solar, wind, and hydro power now account for 51% of the global electricity mix. This milestone comes five years ahead of previous predictions. The surge is driven by massive solar farm installations in deserts and offshore wind projects in the North Sea. Experts say this tipping point makes the net-zero 2050 goal increasingly achievable, though challenges in battery storage infrastructure remain to be solved. Governments worldwide are now shifting subsidies from fossil fuels to grid modernization projects.',
    author: 'Lisa Green',
    source: 'EcoWorld',
    url: '#',
    imageUrl: getMockImage('Solar Panels Wind Turbines Green Energy'),
    publishedAt: '2025-02-15T09:30:00Z',
    category: Category.GENERAL,
    language: Language.ENGLISH
  },
  {
    id: '8',
    title: 'Next-Gen VR Headset Redefines Immersive Gaming',
    description: 'The highly anticipated "Visionary X" headset launches with haptic suits, promising a gaming experience indistinguishable from reality.',
    content: 'Gamers lined up for blocks to get their hands on the new Visionary X VR system. Featuring 8K resolution per eye and neural-interface controllers, the device claims to eliminate motion sickness entirely. Early reviews praise the "Full-Dive" mode, which uses non-invasive sensors to detect player intention, making controller lag a thing of the past. The launch title, "Cyber Odyssey," is already breaking sales records, selling 2 million copies in the first 24 hours. Industry analysts predict this device will also revolutionize remote work and virtual tourism.',
    author: 'Tech Guru',
    source: 'Gadget Now',
    url: '#',
    imageUrl: getMockImage('Virtual Reality Headset Gaming Future'),
    publishedAt: '2025-02-14T16:45:00Z',
    category: Category.ENTERTAINMENT,
    language: Language.ENGLISH
  },
  {
    id: '9',
    title: 'Ancient City Discovered Beneath the Amazon Canopy',
    description: 'Using LiDAR technology, archaeologists have mapped a massive urban network hidden under the jungle for centuries.',
    content: 'A civilization previously unknown to history has been revealed in the Amazon basin. LiDAR scans show a complex network of roads, pyramids, and reservoirs spanning hundreds of kilometers. The city, tentatively named "Xylos," could have housed up to 100,000 people. This discovery challenges the long-held belief that the Amazon could not support large-scale agricultural societies. Expeditions are currently being organized to explore the ruins on foot, with hopes of finding artifacts that could shed light on the culture and daily life of its inhabitants.',
    author: 'Indiana Croft',
    source: 'History Unveiled',
    url: '#',
    imageUrl: getMockImage('Ancient Ruins Jungle Discovery'),
    publishedAt: '2025-02-13T13:20:00Z',
    category: Category.SCIENCE,
    language: Language.ENGLISH
  },
  {
    id: '10',
    title: 'Breakthrough in Vertical Farming Feeds Megacities',
    description: 'New skyscraper farms are producing 100x more yield per acre, offering a solution to urban food security.',
    content: 'Vertical farming startup "SkyHarvest" has unveiled a 50-story agricultural tower in the heart of the metropolis. Using aeroponics and AI-driven light cycles, the tower produces fresh vegetables, fruits, and even grains year-round with 95% less water than traditional farming. This model drastically reduces transportation emissions, as food is grown blocks away from where it is consumed. City officials plan to replicate this design in five more districts by next year, potentially making the city self-sufficient in produce production.',
    author: 'Mark Farmer',
    source: 'Urban Living',
    url: '#',
    imageUrl: getMockImage('Vertical Farming Skyscraper City Future'),
    publishedAt: '2025-02-12T07:15:00Z',
    category: Category.TECHNOLOGY,
    language: Language.ENGLISH
  },
  {
    id: '11',
    title: 'Electric Aviation Takes Off with First Commercial Flight',
    description: 'The first fully electric commercial airliner completed its maiden voyage today, marking a new era of green travel.',
    content: 'History was made at 9:00 AM today as the "E-Liner 500" touched down after a successful 2-hour flight between London and Paris. Powered entirely by high-density solid-state batteries, the aircraft creates zero carbon emissions and reduces noise pollution by 80%. Passengers described the flight as "eerily quiet" and smooth. The airline, EcoAir, plans to roll out a fleet of 50 such planes by 2027, focusing on short-haul regional routes. This success has sparked a race among major manufacturers to electrify their fleets.',
    author: 'Aviation Weekly',
    source: 'Sky News',
    url: '#',
    imageUrl: getMockImage('Electric Airplane Flying Blue Sky'),
    publishedAt: '2025-02-11T09:00:00Z',
    category: Category.TECHNOLOGY,
    language: Language.ENGLISH
  },
  {
    id: '12',
    title: 'Massive Ocean Cleanup Project Reaches Milestone',
    description: 'The Great Pacific Garbage Patch is shrinking as new autonomous cleanup systems remove tons of plastic daily.',
    content: 'The "OceanSaver" initiative reported today that they have successfully removed over 50,000 tons of plastic waste from the Pacific Ocean this year. Their fleet of autonomous, solar-powered vessels uses advanced AI to detect and collect floating debris without harming marine life. The collected plastic is being recycled into construction materials and fabrics. Marine biologists have already observed a return of certain fish species to previously polluted areas. The project aims to reduce the patch size by 50% within the next five years.',
    author: 'Marine Watch',
    source: 'Blue Planet',
    url: '#',
    imageUrl: getMockImage('Ocean Cleanup Ship Plastic Sea'),
    publishedAt: '2025-02-10T14:20:00Z',
    category: Category.SCIENCE,
    language: Language.ENGLISH
  },
  {
    id: '13',
    title: 'Quantum Internet Prototype Successfully Tested',
    description: 'Scientists have achieved stable quantum teleportation of data over a municipal network, paving the way for unhackable internet.',
    content: 'In a joint experiment between three major universities, researchers successfully transmitted data via quantum entanglement over a 50km fiber optic network. Unlike traditional internet, which sends bits as 0s or 1s, the quantum internet uses qubits, allowing for instant and perfectly secure communication. Any attempt to intercept the data would immediately alter it, alerting the receiver. While currently limited to low bandwidths, this prototype proves the feasibility of a global quantum network, which could revolutionize cybersecurity and distributed computing.',
    author: 'Dr. Quantum',
    source: 'Science Daily',
    url: '#',
    imageUrl: getMockImage('Quantum Computer Internet Fiber Optic'),
    publishedAt: '2025-02-09T11:45:00Z',
    category: Category.TECHNOLOGY,
    language: Language.ENGLISH
  },
  {
    id: '14',
    title: 'Medical Nanobots Complete First Human Trials',
    description: 'Microscopic robots designed to hunt and destroy cancer cells have shown a 99% success rate in early clinical trials.',
    content: 'The FDA has fast-tracked the approval process for "NanoCure," a treatment involving millions of microscopic bots injected into the bloodstream. These nanobots are programmed to identify specific markers on tumor cells and deliver targeted drug payloads directly to the source. In the phase 1 trial involving 20 patients, 19 showed complete remission within three months with minimal side effects. This targeted approach avoids the widespread damage to healthy tissue caused by traditional chemotherapy. Doctors are calling it the "magic bullet" of oncology.',
    author: 'Health Correspondent',
    source: 'MedTech News',
    url: '#',
    imageUrl: getMockImage('Nanobots Medical Bloodstream Science'),
    publishedAt: '2025-02-08T08:30:00Z',
    category: Category.HEALTH,
    language: Language.ENGLISH
  },
  {
    id: '15',
    title: 'Smart City Initiative Reduces Energy Consumption by 40%',
    description: 'The city-wide integration of AI traffic management and smart grids has drastically lowered the carbon footprint.',
    content: 'After one year of operation, the "Smart Metropolis" project has released its first annual report. By using AI to optimize traffic light timings, street lighting, and building HVAC systems, the city has reduced its total energy consumption by 40%. Commute times have also improved by 25% due to adaptive traffic flow management. Residents report cleaner air and lower utility bills. The success of this pilot program has attracted the attention of mayors from fifty other major cities who are now looking to adopt similar technologies.',
    author: 'Urban Planner',
    source: 'City Gazette',
    url: '#',
    imageUrl: getMockImage('Smart City Future Night Lights AI'),
    publishedAt: '2025-02-07T18:10:00Z',
    category: Category.GENERAL,
    language: Language.ENGLISH
  }
];

export const TRANSLATIONS: Record<Language, UIStrings> = {
  [Language.ENGLISH]: {
    appName: 'Nexara',
    latestNews: 'Latest News',
    search: 'Search',
    searchPlaceholder: 'Search news...',
    bookmarks: 'Bookmarks',
    settings: 'Settings',
    readMore: 'Read Full Story',
    summarize: 'Summarize with AI',
    summary: 'AI Summary',
    generatingSummary: 'Generating summary...',
    source: 'Source',
    published: 'Published',
    share: 'Share',
    home: 'Home',
    categories: 'Categories',
    noBookmarks: 'No bookmarks yet.',
    saved: 'Article saved',
    removed: 'Article removed',
    refresh: 'Refresh News',
    loading: 'Fetching latest news...',
    generateImage: 'Generate AI Image',
    generatingImage: 'Painting...',
    imageGenerated: 'Image generated!',
    failedToGenerate: 'Failed to generate image',
    cat_General: 'General',
    cat_Technology: 'Technology',
    cat_Sports: 'Sports',
    cat_Business: 'Business',
    cat_Entertainment: 'Entertainment',
    cat_Health: 'Health',
    cat_Science: 'Science',
    cat_Politics: 'Politics'
  },
  [Language.HINDI]: {
    appName: 'नेक्सारा',
    latestNews: 'ताज़ा ख़बरें',
    search: 'खोजें',
    searchPlaceholder: 'खबरें खोजें...',
    bookmarks: 'बुकमार्क',
    settings: 'सेटिंग्स',
    readMore: 'पूरी खबर पढ़ें',
    summarize: 'AI सारांश',
    summary: 'AI सारांश',
    generatingSummary: 'सारांश बना रहा है...',
    source: 'स्रोत',
    published: 'प्रकाशित',
    share: 'साझा करें',
    home: 'होम',
    categories: 'श्रेणियाँ',
    noBookmarks: 'कोई बुकमार्क नहीं।',
    saved: 'लेख सहेजा गया',
    removed: 'लेख हटाया गया',
    refresh: 'ताज़ा करें',
    loading: 'ताज़ा खबरें ला रहा है...',
    generateImage: 'AI चित्र बनाएं',
    generatingImage: 'चित्र बना रहा है...',
    imageGenerated: 'चित्र तैयार है!',
    failedToGenerate: 'चित्र बनाने में विफल',
    cat_General: 'सामान्य',
    cat_Technology: 'प्रौद्योगिकी',
    cat_Sports: 'खेल',
    cat_Business: 'व्यापार',
    cat_Entertainment: 'मनोरंजन',
    cat_Health: 'स्वास्थ्य',
    cat_Science: 'विज्ञान',
    cat_Politics: 'राजनीति'
  },
  [Language.TAMIL]: {
    appName: 'நெக்சாரா',
    latestNews: 'சமீபத்திய செய்திகள்',
    search: 'தேடல்',
    searchPlaceholder: 'செய்திகளைத் தேடுங்கள்...',
    bookmarks: 'புக்மார்க்குகள்',
    settings: 'அமைப்புகள்',
    readMore: 'முழு கதையையும் படியுங்கள்',
    summarize: 'AI சுருக்கம்',
    summary: 'AI சுருக்கம்',
    generatingSummary: 'சுருக்கம் உருவாக்கப்படுகிறது...',
    source: 'ஆதாரம்',
    published: 'வெளியிடப்பட்டது',
    share: 'பகிரவும்',
    home: 'முகப்பு',
    categories: 'வகைகள்',
    noBookmarks: 'புக்மார்க்குகள் இல்லை.',
    saved: 'கட்டுரை சேமிக்கப்பட்டது',
    removed: 'கட்டுரை அகற்றப்பட்டது',
    refresh: 'புதுப்பிக்கவும்',
    loading: 'செய்திகள் ஏற்றப்படுகின்றன...',
    generateImage: 'AI படம்',
    generatingImage: 'படம் உருவாகிறது...',
    imageGenerated: 'படம் தயார்!',
    failedToGenerate: 'படம் உருவாக்க முடியவில்லை',
    cat_General: 'பொது',
    cat_Technology: 'தொழில்நுட்பம்',
    cat_Sports: 'விளையாட்டு',
    cat_Business: 'வணிகம்',
    cat_Entertainment: 'பொழுதுபோக்கு',
    cat_Health: 'சுகாதாரம்',
    cat_Science: 'அறிவியல்',
    cat_Politics: 'அரசியல்'
  },
  [Language.TELUGU]: {
    appName: 'నెక్సారా',
    latestNews: 'తాజా వార్తలు',
    search: 'శోధన',
    searchPlaceholder: 'వార్తలను శోధించండి...',
    bookmarks: 'బుక్‌మార్క్‌లు',
    settings: 'సెట్టింగ్‌లు',
    readMore: 'పూర్తి కథనాన్ని చదవండి',
    summarize: 'AI సారాంశం',
    summary: 'AI సారాంశం',
    generatingSummary: 'సారాంశం రూపొందించబడుతోంది...',
    source: 'మూలం',
    published: 'ప్రచురించబడింది',
    share: 'భాగస్వామ్యం',
    home: 'హోమ్',
    categories: 'వర్గాలు',
    noBookmarks: 'బుక్‌మార్క్‌లు లేవు.',
    saved: 'వ్యాసం సేవ్ చేయబడింది',
    removed: 'వ్యాసం తీసివేయబడింది',
    refresh: 'తాజాకరించండి',
    loading: 'వార్తలు లోడ్ అవుతున్నాయి...',
    generateImage: 'AI చిత్రం',
    generatingImage: 'చిత్రం గీయడం...',
    imageGenerated: 'చిత్రం రూపొందించబడింది!',
    failedToGenerate: 'చిత్రం రూపొందించడంలో విఫలమైంది',
    cat_General: 'సాధారణ',
    cat_Technology: 'టెక్నాలజీ',
    cat_Sports: 'క్రీడలు',
    cat_Business: 'వ్యాపారం',
    cat_Entertainment: 'వినోదం',
    cat_Health: 'ఆరోగ్యం',
    cat_Science: 'సైన్స్',
    cat_Politics: 'రాజకీయాలు'
  },
  [Language.MALAYALAM]: {
    appName: 'നെക്സാറ',
    latestNews: 'ഏറ്റവും പുതിയ വാർത്തകൾ',
    search: 'തിരയുക',
    searchPlaceholder: 'വാർത്തകൾ തിരയുക...',
    bookmarks: 'ബുക്ക്മാർക്കുകൾ',
    settings: 'ക്രമീകരണങ്ങൾ',
    readMore: 'പൂർണ്ണ വാർത്ത വായിക്കുക',
    summarize: 'AI സംഗ്രഹം',
    summary: 'AI സംഗ്രഹം',
    generatingSummary: 'സംഗ്രഹം തയ്യാറാക്കുന്നു...',
    source: 'ഉറവിടം',
    published: 'പ്രസിദ്ധീകരിച്ചത്',
    share: 'പങ്കിടുക',
    home: 'ഹോം',
    categories: 'വിഭാഗങ്ങൾ',
    noBookmarks: 'ബുക്ക്മാർക്കുകൾ ഒന്നുമില്ല.',
    saved: 'ലേഖനം സേവ് ചെയ്തു',
    removed: 'ലേഖനം നീക്കം ചെയ്തു',
    refresh: 'പുതുക്കുക',
    loading: 'വാർത്തകൾ എടുക്കുന്നു...',
    generateImage: 'AI ചിത്രം',
    generatingImage: 'ചിത്രം സൃഷ്ടിക്കുന്നു...',
    imageGenerated: 'ചിത്രം തയ്യാറാണ്!',
    failedToGenerate: 'ചിത്രം സൃഷ്ടിക്കാൻ കഴിഞ്ഞില്ല',
    cat_General: 'പൊതുവായവ',
    cat_Technology: 'സാങ്കേതികവിദ്യ',
    cat_Sports: 'കായികം',
    cat_Business: 'ബിസിനസ്സ്',
    cat_Entertainment: 'വിനോദം',
    cat_Health: ' ആരോഗ്യം',
    cat_Science: 'ശാസ്ത്രം',
    cat_Politics: 'രാഷ്ട്രീയം'
  },
  [Language.SPANISH]: {
    appName: 'Nexara',
    latestNews: 'Últimas Noticias',
    search: 'Buscar',
    searchPlaceholder: 'Buscar noticias...',
    bookmarks: 'Guardados',
    settings: 'Ajustes',
    readMore: 'Leer más',
    summarize: 'Resumir con IA',
    summary: 'Resumen IA',
    generatingSummary: 'Generando resumen...',
    source: 'Fuente',
    published: 'Publicado',
    share: 'Compartir',
    home: 'Inicio',
    categories: 'Categorías',
    noBookmarks: 'Sin marcadores.',
    saved: 'Artículo guardado',
    removed: 'Artículo eliminado',
    refresh: 'Actualizar',
    loading: 'Cargando noticias...',
    generateImage: 'Generar imagen IA',
    generatingImage: 'Pintando...',
    imageGenerated: '¡Imagen generada!',
    failedToGenerate: 'Error al generar imagen',
    cat_General: 'General',
    cat_Technology: 'Tecnología',
    cat_Sports: 'Deportes',
    cat_Business: 'Negocios',
    cat_Entertainment: 'Entretenimiento',
    cat_Health: 'Salud',
    cat_Science: 'Ciencia',
    cat_Politics: 'Política'
  },
  [Language.FRENCH]: {
    appName: 'Nexara',
    latestNews: 'Dernières Nouvelles',
    search: 'Recherche',
    searchPlaceholder: 'Rechercher des actualités...',
    bookmarks: 'Favoris',
    settings: 'Paramètres',
    readMore: 'Lire la suite',
    summarize: 'Résumer avec IA',
    summary: 'Résumé IA',
    generatingSummary: 'Génération du résumé...',
    source: 'Source',
    published: 'Publié',
    share: 'Partager',
    home: 'Accueil',
    categories: 'Catégories',
    noBookmarks: 'Aucun favori.',
    saved: 'Article enregistré',
    removed: 'Article supprimé',
    refresh: 'Actualiser',
    loading: 'Chargement des actualités...',
    generateImage: 'Générer image IA',
    generatingImage: 'Peinture...',
    imageGenerated: 'Image générée!',
    failedToGenerate: 'Échec de la génération',
    cat_General: 'Général',
    cat_Technology: 'Technologie',
    cat_Sports: 'Sports',
    cat_Business: 'Affaires',
    cat_Entertainment: 'Divertissement',
    cat_Health: 'Santé',
    cat_Science: 'Science',
    cat_Politics: 'Politique'
  },
  [Language.GERMAN]: {
    appName: 'Nexara',
    latestNews: 'Neueste Nachrichten',
    search: 'Suche',
    searchPlaceholder: 'Nachrichten suchen...',
    bookmarks: 'Lesezeichen',
    settings: 'Einstellungen',
    readMore: 'Weiterlesen',
    summarize: 'Mit KI zusammenfassen',
    summary: 'KI-Zusammenfassung',
    generatingSummary: 'Zusammenfassung wird erstellt...',
    source: 'Quelle',
    published: 'Veröffentlicht',
    share: 'Teilen',
    home: 'Startseite',
    categories: 'Kategorien',
    noBookmarks: 'Keine Lesezeichen.',
    saved: 'Artikel gespeichert',
    removed: 'Artikel entfernt',
    refresh: 'Aktualisieren',
    loading: 'Nachrichten laden...',
    generateImage: 'KI-Bild generieren',
    generatingImage: 'Malen...',
    imageGenerated: 'Bild generiert!',
    failedToGenerate: 'Bild konnte nicht generiert werden',
    cat_General: 'Allgemein',
    cat_Technology: 'Technologie',
    cat_Sports: 'Sport',
    cat_Business: 'Wirtschaft',
    cat_Entertainment: 'Unterhaltung',
    cat_Health: 'Gesundheit',
    cat_Science: 'Wissenschaft',
    cat_Politics: 'Politik'
  },
  [Language.CHINESE]: {
    appName: '奈克萨拉',
    latestNews: '最新新闻',
    search: '搜索',
    searchPlaceholder: '搜索新闻...',
    bookmarks: '书签',
    settings: '设置',
    readMore: '阅读全文',
    summarize: 'AI 摘要',
    summary: 'AI 摘要',
    generatingSummary: '正在生成摘要...',
    source: '来源',
    published: '发布于',
    share: '分享',
    home: '首页',
    categories: '分类',
    noBookmarks: '暂无书签。',
    saved: '文章已保存',
    removed: '文章已移除',
    refresh: '刷新',
    loading: '正在获取新闻...',
    generateImage: '生成 AI 图片',
    generatingImage: '正在绘制...',
    imageGenerated: '图片已生成！',
    failedToGenerate: '图片生成失败',
    cat_General: '综合',
    cat_Technology: '科技',
    cat_Sports: '体育',
    cat_Business: '商业',
    cat_Entertainment: '娱乐',
    cat_Health: '健康',
    cat_Science: '科学',
    cat_Politics: '政治'
  }
};